#! /bin/bash

set -e

WHO=$(whoami)

if [[ $WHO != "root" ]]
then
	echo "Please Run as Root"
	exit 100
fi

### GLOBAL ENV VARS ###
WIN_DRIVE=$(os-prober | cut -d/ -f1-3 | tr -d '@')
SDB_EFI=$(bootctl -x)
SDB_DRIVE=$(findmnt "$SDB_EFI" | tail +2 | cut -f2 -d" ")
MACHINE_ID=$(cat /etc/machine-id)
CURRENT_CMD=$(bootctl list | grep options | head -n1 | cut -f2- -d":")
### End of region ###

### Help message
if [[ $1 == '-h' ]] ||  [[ $1 == '--help' ]]
then
cat << EOF
 __| |____________________________________________________________________________________________________________________________
(__| |____________________________________________________________________________________________________________________________)
   | |  update-systemd-boot
PikaOS Wrapper for updating systemd-boot configrations

Usage:
update-systemd-boot [arguments if needed]

Arguments:
-h | | --help: Displays this help message.
-w | | --with-os-prober: Does the usual Linux entry generation along side using os prober for detecting Windows EFI partitions.
-x | | --only-os-prober: Uses os prober for detecting Windows EFI partitions without the usual Linux entry generation.
-o | | --change-options: Brings up a text editor to modify the Linux commandline boot options.
 __| |____________________________________________________________________________________________________________________________
(__|_|____________________________________________________________________________________________________________________________)
EOF
exit
fi

### End of region ###

### Print system info ###
if [ -z "$SDB_EFI" ]
then
	echo "Critical Error! systemd-boot isn't installed." & exit 1
else
	echo "systemd-boot EFI path: $SDB_EFI"
fi

if [ -z "$SDB_DRIVE" ]
then
	echo "systemd-boot partition: None"
else
	echo "systemd-boot partition: $SDB_DRIVE"
fi

if [ -z "$WIN_DRIVE" ]
then
	echo "Windows EFI partition: None"
else
	echo "Windows EFI partition: $WIN_DRIVE"
fi

if [ -z "$MACHINE_ID" ]
then
	echo "Machine ID: None"
else
	echo "Machine ID: $MACHINE_ID"
fi

if [ -z "$CURRENT_CMD" ]
then
	echo "Kernel Boot Options: None"
else
	echo "Kernel Boot Options: $CURRENT_CMD"
fi


### Linux Kernel Images Detection ###
if [[ $1 == '-x' ]] ||  [[ $1 == '--only-os-prober' ]]
then
	set -e
else
cat << EOF
 _______________________________________
< Detecting Linux Kernel Images in /boot >
 ---------------------------------------
   \'
    \'
        .--.
       |o_o |
       |:_/ |
      //   \ )
     (|     | )
    /'\_   _/;/
    \___)=(___/

EOF

for kernels in $(find /boot/vmlinuz* | cut -d '-' -f2- | grep -vi vmlinuz); do echo "Detected Kernel: $kernels" ; done
### End of region ###

### Linux Kernel Entry Generation ###
echo "Removing old entries."
rm -rfv $SDB_EFI/"$MACHINE_ID"
rm -rfv $SDB_EFI/loader/entries/"$MACHINE_ID"*
echo "Generating new entries."
for kernels in $(find /boot/vmlinuz* | cut -d '-' -f2- | grep -vi vmlinuz); do echo "Generating entry for $kernels" && kernel-install add $kernels /boot/vmlinuz-$kernels /boot/initrd.img-$kernels || echo "Failed to Generate an entry for $kernels"; done 
### End of region ###

### Change kernel options ###
if [[ $1 == '-o' ]] ||  [[ $1 == '--change-options' ]]
then
	echo "Changing Linux Boot Options"
	BOOTCTL_CMD=$(bootctl list | grep options | head -n1 | cut -f2- -d":")
	mkdir -p /tmp/update-systemd-boot/
	if [ ! -f /tmp/update-systemd-boot/options ]
	then
		echo $BOOTCTL_CMD > /tmp/update-systemd-boot/options
		editor /tmp/update-systemd-boot/options
	fi
	for entries in $(find $SDB_EFI/loader/entries/$MACHINE_ID*); do sed -i "s#$BOOTCTL_CMD#$(cat /tmp/update-systemd-boot/options)#" "$entries"; done
	echo "Changed Linux Boot Options"
	echo "from: $BOOTCTL_CMD"
	echo "to: $(cat /tmp/update-systemd-boot/options)"
	rm -rf /tmp/update-systemd-boot/
fi
fi
### End of region ###

### Windows Boot Manager Detection ###
if [[ $1 == '-w' ]] ||  [[ $1 == '--with-os-prober' ]] || [[ $1 == '-x' ]] ||  [[ $1 == '--only-os-prober' ]]
then
if [ -z "$WIN_DRIVE" ]
then
echo "os-prober has not detected a Windows EFI partition! no action is needed." & exit 0
else
if [[ "$WIN_DRIVE" == "$SDB_DRIVE" ]]
then
cat << EOF
 ________________________________
< Detecting Windows Boot Manager >
 --------------------------------
   \'
    \'	   _.-;;-._
    '-..-'|   ||   |
    '-..-'|_.-;;-._|
    '-..-'|   ||   |
    '-..-'|_.-''-._|
EOF
echo "systemd-boot EFI and Windows EFI partition are the SAME! no action is needed." & exit 0
else
cat << EOF
 ________________________________
< Detecting Windows Boot Manager >
 --------------------------------
   \'
    \'	   _.-;;-._
    '-..-'|   ||   |
    '-..-'|_.-;;-._|
    '-..-'|   ||   |
    '-..-'|_.-''-._|
EOF
echo "os-prober has detected a Windows EFI partition! adding to systemd-boot efi."
mkdir -p /tmp/WIN_DRIVE
mount "$WIN_DRIVE" /tmp/WIN_DRIVE
cp -ax /tmp/WIN_DRIVE/EFI/Microsoft $SDB_EFI/EFI/Microsoft
umount /tmp/WIN_DRIVE
exit 0
fi
fi
fi
### End of region ###
